---
- name: Deploy VM from template using vSphere
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    template: "{{ template_name }}"
    datastore: "{{ datastore_name }}"
    state: poweredon
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
    networks:
      - name: "{{ vm_network }}"
        type: "{{ vm_ip_config.type }}"
        ip: "{{ vm_ip_config.ip | default(omit) }}"
        netmask: "{{ vm_ip_config.netmask | default(omit) }}"
        gateway: "{{ vm_ip_config.gateway | default(omit) }}"
        dns_servers: "{{ vm_ip_config.dns_servers | default(omit) }}"
    wait_for_ip_address: yes
